/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module delayed_serial_adder(clk, rst, x, a, y_in, y_out);
  wire _0_;
  wire _1_;
  wire _2_;
  input a;
  wire a;
  input clk;
  wire clk;
  wire last_carry;
  wire last_carry_next;
  input rst;
  wire rst;
  input x;
  wire x;
  input y_in;
  wire y_in;
  output y_out;
  wire y_out;
  wire y_out_next;
  sky130_fd_sc_hd__nand3_2 _3_ (
    .A(last_carry),
    .B(a),
    .C(x),
    .Y(_0_)
  );
  sky130_fd_sc_hd__a21o_2 _4_ (
    .A1(a),
    .A2(x),
    .B1(last_carry),
    .X(_1_)
  );
  sky130_fd_sc_hd__nand2_2 _5_ (
    .A(_0_),
    .B(_1_),
    .Y(_2_)
  );
  sky130_fd_sc_hd__xnor2_2 _6_ (
    .A(y_in),
    .B(_2_),
    .Y(y_out_next)
  );
  sky130_fd_sc_hd__a21bo_2 _7_ (
    .A1(y_in),
    .A2(_1_),
    .B1_N(_0_),
    .X(last_carry_next)
  );
  sky130_fd_sc_hd__dfrtp_2 _8_ (
    .CLK(clk),
    .D(last_carry_next),
    .Q(last_carry),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_2 _9_ (
    .CLK(clk),
    .D(y_out_next),
    .Q(y_out),
    .RESET_B(rst)
  );
endmodule

module spm(clk, rst, x, a, y);
  wire _0_;
  input [31:0] a;
  wire [31:0] a;
  input clk;
  wire clk;
  input rst;
  wire rst;
  input x;
  wire x;
  output y;
  wire y;
  wire \y_chain[10] ;
  wire \y_chain[11] ;
  wire \y_chain[12] ;
  wire \y_chain[13] ;
  wire \y_chain[14] ;
  wire \y_chain[15] ;
  wire \y_chain[16] ;
  wire \y_chain[17] ;
  wire \y_chain[18] ;
  wire \y_chain[19] ;
  wire \y_chain[1] ;
  wire \y_chain[20] ;
  wire \y_chain[21] ;
  wire \y_chain[22] ;
  wire \y_chain[23] ;
  wire \y_chain[24] ;
  wire \y_chain[25] ;
  wire \y_chain[26] ;
  wire \y_chain[27] ;
  wire \y_chain[28] ;
  wire \y_chain[29] ;
  wire \y_chain[2] ;
  wire \y_chain[30] ;
  wire \y_chain[31] ;
  wire \y_chain[3] ;
  wire \y_chain[4] ;
  wire \y_chain[5] ;
  wire \y_chain[6] ;
  wire \y_chain[7] ;
  wire \y_chain[8] ;
  wire \y_chain[9] ;
  sky130_fd_sc_hd__conb_1 _1_ (
    .LO(_0_)
  );
  delayed_serial_adder \dsa[0]  (
    .a(a[31]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(_0_),
    .y_out(\y_chain[1] )
  );
  delayed_serial_adder \dsa[10]  (
    .a(a[21]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[10] ),
    .y_out(\y_chain[11] )
  );
  delayed_serial_adder \dsa[11]  (
    .a(a[20]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[11] ),
    .y_out(\y_chain[12] )
  );
  delayed_serial_adder \dsa[12]  (
    .a(a[19]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[12] ),
    .y_out(\y_chain[13] )
  );
  delayed_serial_adder \dsa[13]  (
    .a(a[18]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[13] ),
    .y_out(\y_chain[14] )
  );
  delayed_serial_adder \dsa[14]  (
    .a(a[17]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[14] ),
    .y_out(\y_chain[15] )
  );
  delayed_serial_adder \dsa[15]  (
    .a(a[16]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[15] ),
    .y_out(\y_chain[16] )
  );
  delayed_serial_adder \dsa[16]  (
    .a(a[15]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[16] ),
    .y_out(\y_chain[17] )
  );
  delayed_serial_adder \dsa[17]  (
    .a(a[14]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[17] ),
    .y_out(\y_chain[18] )
  );
  delayed_serial_adder \dsa[18]  (
    .a(a[13]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[18] ),
    .y_out(\y_chain[19] )
  );
  delayed_serial_adder \dsa[19]  (
    .a(a[12]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[19] ),
    .y_out(\y_chain[20] )
  );
  delayed_serial_adder \dsa[1]  (
    .a(a[30]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[1] ),
    .y_out(\y_chain[2] )
  );
  delayed_serial_adder \dsa[20]  (
    .a(a[11]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[20] ),
    .y_out(\y_chain[21] )
  );
  delayed_serial_adder \dsa[21]  (
    .a(a[10]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[21] ),
    .y_out(\y_chain[22] )
  );
  delayed_serial_adder \dsa[22]  (
    .a(a[9]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[22] ),
    .y_out(\y_chain[23] )
  );
  delayed_serial_adder \dsa[23]  (
    .a(a[8]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[23] ),
    .y_out(\y_chain[24] )
  );
  delayed_serial_adder \dsa[24]  (
    .a(a[7]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[24] ),
    .y_out(\y_chain[25] )
  );
  delayed_serial_adder \dsa[25]  (
    .a(a[6]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[25] ),
    .y_out(\y_chain[26] )
  );
  delayed_serial_adder \dsa[26]  (
    .a(a[5]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[26] ),
    .y_out(\y_chain[27] )
  );
  delayed_serial_adder \dsa[27]  (
    .a(a[4]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[27] ),
    .y_out(\y_chain[28] )
  );
  delayed_serial_adder \dsa[28]  (
    .a(a[3]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[28] ),
    .y_out(\y_chain[29] )
  );
  delayed_serial_adder \dsa[29]  (
    .a(a[2]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[29] ),
    .y_out(\y_chain[30] )
  );
  delayed_serial_adder \dsa[2]  (
    .a(a[29]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[2] ),
    .y_out(\y_chain[3] )
  );
  delayed_serial_adder \dsa[30]  (
    .a(a[1]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[30] ),
    .y_out(\y_chain[31] )
  );
  delayed_serial_adder \dsa[31]  (
    .a(a[0]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[31] ),
    .y_out(y)
  );
  delayed_serial_adder \dsa[3]  (
    .a(a[28]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[3] ),
    .y_out(\y_chain[4] )
  );
  delayed_serial_adder \dsa[4]  (
    .a(a[27]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[4] ),
    .y_out(\y_chain[5] )
  );
  delayed_serial_adder \dsa[5]  (
    .a(a[26]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[5] ),
    .y_out(\y_chain[6] )
  );
  delayed_serial_adder \dsa[6]  (
    .a(a[25]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[6] ),
    .y_out(\y_chain[7] )
  );
  delayed_serial_adder \dsa[7]  (
    .a(a[24]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[7] ),
    .y_out(\y_chain[8] )
  );
  delayed_serial_adder \dsa[8]  (
    .a(a[23]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[8] ),
    .y_out(\y_chain[9] )
  );
  delayed_serial_adder \dsa[9]  (
    .a(a[22]),
    .clk(clk),
    .rst(rst),
    .x(x),
    .y_in(\y_chain[9] ),
    .y_out(\y_chain[10] )
  );
endmodule
